NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0


In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  

end_time = process_time()

print(end_time - start_time)

0.0


Numpy Arrays

In [5]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape

(4,)

In [9]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [11]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [12]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.89346233 0.63625592 0.80656943 0.81105371]
 [0.74976709 0.28156291 0.43386297 0.47435482]
 [0.66079915 0.91664151 0.08246947 0.1959713 ]]


In [17]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[39 22 77 22 10]
 [27 12 53 64 29]
 [14 87 94 75 66]]


In [18]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [20]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [21]:
c = np.random.randint(10,90,(5,5))
print(c)

[[37 33 19 80 55]
 [46 45 62 83 68]
 [51 59 36 74 60]
 [76 14 52 27 52]
 [75 13 49 79 59]]


In [22]:
# array dimension
print(c.shape)

(5, 5)


In [23]:
# number of dimensions
print(c.ndim)

2


In [24]:
# number of elements in an array
print(c.size)

25


In [25]:
# checking the data type of the values in the array
print(c.dtype)

int32


Mathematical operations on a np array

In [26]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [27]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [28]:
print(a)
print(b)

[[4 3 7]
 [4 6 3]
 [5 9 9]]
[[10 16 17]
 [14 15 16]
 [13 17 14]]


In [29]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[14 19 24]
 [18 21 19]
 [18 26 23]]
[[ -6 -13 -10]
 [-10  -9 -13]
 [ -8  -8  -5]]
[[ 40  48 119]
 [ 56  90  48]
 [ 65 153 126]]
[[0.4        0.1875     0.41176471]
 [0.28571429 0.4        0.1875    ]
 [0.38461538 0.52941176 0.64285714]]


In [30]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [31]:
print(a)
print(b)

[[6 7 0]
 [5 3 1]
 [3 0 7]]
[[14 14 15]
 [10 18 18]
 [12 15 15]]


In [32]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[20 21 15]
 [15 21 19]
 [15 15 22]]
[[ -8  -7 -15]
 [ -5 -15 -17]
 [ -9 -15  -8]]
[[ 84  98   0]
 [ 50  54  18]
 [ 36   0 105]]
[[0.42857143 0.5        0.        ]
 [0.5        0.16666667 0.05555556]
 [0.25       0.         0.46666667]]


Array Manipulation

In [33]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 6 7]
 [0 4 2]]
(2, 3)


In [34]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[8 0]
 [6 4]
 [7 2]]
(3, 2)


In [35]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 7 2]
 [1 8 9]]
(2, 3)


In [36]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[0 1]
 [7 8]
 [2 9]]
(3, 2)


In [37]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 6 0]
 [8 7 9]]
(2, 3)


In [38]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 6]
 [0 8]
 [7 9]]
(3, 2)
