Importing Numpy Library

In [1]:
import numpy as np

**Matrix Addition**

Two Matrices can be added only if they have the same shape

In [2]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [3]:
print(A)

[[2 3]
 [4 5]]


In [4]:
print(B)

[[6 7]
 [8 9]]


In [5]:
A.shape

(2, 2)

In [6]:
B.shape

(2, 2)

Adding two Matrices

In [7]:
sum = A + B

In [8]:
print(sum)

[[ 8 10]
 [12 14]]


In [9]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [10]:
print(matrix_1)

[[8 4 5]
 [4 2 4]
 [6 6 9]]


In [11]:
print(matrix_2)

[[ 1 14 19]
 [ 3  4 11]
 [ 2  3  0]]


In [12]:
sum = np.add(matrix_1, matrix_2)

In [13]:
print(sum)

[[ 9 18 24]
 [ 7  6 15]
 [ 8  9  9]]


In [14]:
# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

In [15]:
sum_2 = np.add(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because shape of matrix_3 and matrix_4 are different

**Matrix Subtraction**

In [16]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [17]:
print(A)

[[2 3]
 [4 5]]


In [18]:
print(B)

[[6 7]
 [8 9]]


In [19]:
difference = A - B

In [20]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [21]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [22]:
print(matrix_1)

[[3 6 1]
 [8 4 9]
 [7 9 3]]


In [23]:
print(matrix_2)

[[ 9  5  5]
 [16  8 11]
 [ 1  0  9]]


In [24]:
diff = np.subtract(matrix_1, matrix_2)

In [25]:
print(diff)

[[-6  1 -4]
 [-8 -4 -2]
 [ 6  9 -6]]


**Multiplying a matrix by a scalar**

In [26]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[6 4 1 4]
 [8 1 2 4]
 [9 7 9 8]
 [3 4 1 8]]


In [27]:
product = np.multiply(x,y)

In [28]:
print(product)

[[30 20  5 20]
 [40  5 10 20]
 [45 35 45 40]
 [15 20  5 40]]


**Multiplying 2 Matrices**

In [29]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [30]:
print(matrix_3)

[[0 4 4]
 [2 4 3]
 [1 3 0]]


In [31]:
print(matrix_4)

[[0 3 2 0]
 [3 2 2 0]
 [3 0 4 1]]


In [32]:
product = np.dot(matrix_3, matrix_4)

In [33]:
print(product)

[[24  8 24  4]
 [21 14 24  3]
 [ 9  9  8  0]]


In [34]:
product.shape

(3, 4)

In [35]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [36]:
product = np.dot(matrix_3, matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

**Element wise Matrix Multiplication**

In [37]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [38]:
print(matrix_3)

[[0 4 0]
 [2 0 2]
 [0 4 2]]


In [39]:
print(matrix_4)

[[4 4 2]
 [2 2 0]
 [0 2 2]]


In [40]:
product = np.multiply(matrix_3, matrix_4)

In [41]:
print(product)

[[ 0 16  0]
 [ 4  0  0]
 [ 0  8  4]]


In [42]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [43]:
product = np.multiply(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [45]:
m1 = np.random.randint(5, size =(3,3))
m2 = np.random.randint(5, size =(3,3))

print(m1)
print(m2)

[[2 0 3]
 [1 1 2]
 [2 1 0]]
[[0 0 2]
 [0 2 4]
 [3 1 2]]


In [47]:
cross_product = np.cross(m1,m2)
print(cross_product)

[[ 0 -4  0]
 [ 0 -4  2]
 [ 2 -4 -1]]


In [48]:
v = np.array([[[1]]])
print(v.shape)

(1, 1, 1)
